### ISSUE TITLE
Why pass directory?

### ISSUE THREAD

**Issue by hboylan** [moon0326/swagger-ui-watcher#7]
Great library! 👍 

Just wondered if there's a specific reason for watching the swagger file's parent directory?

The node-watch spec shows that you can [just watch the file itself](https://www.npmjs.com/package/node-watch#example). Let me know and I can make a PR tonight.

**Comment by moon0326** [comment]
hi @hboylan 

Please correct me If I'm wrong as I haven't used node-watch that much.

If we don't accept the target dir and just watch the main file, I don't think there is a way to detect changes in the other files that are referenced in the main file (1st argument).

We can try to watch the whole directory, but then we need to come up with a rule for the main file's filename because we need to know the main file's filename in order to build the final bundle.

I think we could potential remove 2nd argument by parsing the main file and create a watch list, but I'm not sure if it's worth.

Any suggestions would be welcomed! 

Thanks,
Moon

**Comment by hboylan** [comment]
Ah, I'm still getting familiar with Swagger. Since [splitting](http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html) the specs makes a lot of sense, so does watching the directory.

How about resolving the absolute path to the root file, [find parent dir](https://www.npmjs.com/package/find-parent-dir), and watch that by default?

**Comment by moon0326** [comment]
@hboylan I think that would work. Making a target dir as an optional argument is a good idea :)
